### ISSUE TITLE
Upgrading Product Issue - The enabled_errands parameter is no longer supported

### ISSUE THREAD

**Issue by sba30** [compozed/ops_manager_cli#35]
When upgrading to mySQL 1.9.12, the following error occurs when performing post to /api/v0/installations with opts

Error:

res.code: 400
I, [2017-10-19T15:09:59.523589 #17]  INFO -- : post response body {"errors":["The enabled_errands parameter is no longer supported"]}

**Comment by bonzofenix** [comment]
Which is your current ops manager version?

**Comment by sba30** [comment]
1.10.11

**Comment by bonzofenix** [comment]
which version of the gem are you using?

**Comment by sba30** [comment]
I am using this version ops_manager_cli#0.4.1

**Comment by geofffranks** [comment]
@sba30 says this is fixed
