### ISSUE TITLE
Link to CLA is broken

### ISSUE THREAD

**Issue by kpschuck** [compozed/ops_manager_cli#4]
<img width="564" alt="screen shot 2016-10-05 at 11 39 03 am" src="https://cloud.githubusercontent.com/assets/5521372/19122515/6ab01c74-8af0-11e6-986f-60a684d4bbeb.png">

https://compozed-cla.cfapps.io/agreements/compozed/ops_manager_cli

**Comment by bonzofenix** [comment]
Thanks for finding this! we added the CLA so that you can sign it. Once we have that I will go ahead and merge #3 .
